### ISSUE TITLE
Split KNNRegressor into KNNRegressor and KNNMultitargetRegressor

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/NearestNeighborModels.jl#1]
I think we will come to regret combining the two target_scitypes into the one model. This is already leading to issues - KNNRegressor cannot be used as atomic model in EnsembleModel any more; see [here](https://travis-ci.com/github/alan-turing-institute/MLJ.jl/jobs/412511762), for example).

Generally we have pushed for different models for different input scitypes, so this is the same philosophy. 

@OkonSamuel

**Comment by ablaom** [comment]
@OkonSamuel Just a reminder of this issue, since I know you are working on this

**Comment by OkonSamuel** [comment]
noted
