### ISSUE TITLE
Final Integration Steps

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/NearestNeighborModels.jl#22]
- [x] Add github CI

- [x] Register NearestNeighborModels

- [x] Create a MLJModels branch `nn-migration` that removes `NearestNeighbors` glue code and updates the registry to reflect the migration

- [x] Locally test updated registry in `nn-migration` finds NearestNeighborModels.jl

- [x] Merge  `nn-migration` into dev and master branches of MLJModels and tag a new release.

**Comment by ablaom** [comment]
@OkonSamuel Release version 0.1 when ready, or let me know and I'll do it. I think first time you have to do it using juliahub.

I will take care of the rest of the checklist after the release.
