### ISSUE TITLE
`Rank` docstring

### ISSUE THREAD

**Issue by ParadaCarleton** [alan-turing-institute/NearestNeighborModels.jl#60]
The docstring for `Rank` seems to contain an error: 
```
Assigns each neighbor a weight as a rank such that the closest neighbor get's a weight of `1` and the Kth closest neighbor gets a weight of `K`.
```
This doesn't make sense to me, since it implies that the closest neighbor gets the smallest weight, and the furthest neighbor gets the largest weight. Is the docstring just backwards, or is it supposed to do something else?

**Comment by OkonSamuel** [comment]
@ParadaCarleton Nice catch. This is a bug. It's meant to be reversed. Closest should get more weight and farthest should get less weight. 
Do you want to open a PR to fix this?  Or should I fix it?

**Comment by ParadaCarleton** [comment]
Thank you!
